#!/usr/bin/env bash
# Script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
