#!/usr/bin/env bash
# Configure  Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
red_config="\\tlocation = /redirect_me {\n\\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\\t}"
sudo sed -i "/^server {/a $red_config" /etc/nginx/sites-available/default
sudo service nginx start
