#!/bin/bash
#Script that configures HAproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
  mode http
  balance roundrobin
  server 204106-web-01 52.90.14.186 check
  server 204106-web-02 54.210.88.183 check
EOF
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy restart
