#!/usr/bin/env bash
# Configures a web server to run Nginx
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su nginx -c "service nginx restart"
